export const pokemonColorVariants = {
    card: {
        all: 'bg-custom-all',
        normal: 'bg-custom-normal',
        fire: 'bg-custom-fire',
        water: 'bg-custom-water',
        electric: 'bg-custom-electric',
        grass: 'bg-custom-grass',
        ice: 'bg-custom-ice',
        fighting: 'bg-custom-fighting',
        poison: 'bg-custom-poison',
        ground: 'bg-custom-ground',
        flying: 'bg-custom-flying',
        psychic: 'bg-custom-psychic',
        bug: 'bg-custom-bug',
        rock: 'bg-custom-rock',
        ghost: 'bg-custom-ghost',
        dragon: 'bg-custom-dragon',
        dark: 'bg-custom-dark',
        steel: 'bg-custom-steel',
        fairy: 'bg-custom-fairy',
      },
      tag: {
        normal: 'bg-custom-tag-normal',
        fire: 'bg-custom-tag-fire',
        water: 'bg-custom-tag-water',
        electric: 'bg-custom-tag-electric',
        grass: 'bg-custom-tag-grass',
        ice: 'bg-custom-tag-ice',
        fighting: 'bg-custom-tag-fighting',
        poison: 'bg-custom-tag-poison',
        ground: 'bg-custom-tag-ground',
        flying: 'bg-custom-tag-flying',
        psychic: 'bg-custom-tag-psychic',
        bug: 'bg-custom-tag-bug',
        rock: 'bg-custom-tag-rock',
        ghost: 'bg-custom-tag-ghost',
        dragon: 'bg-custom-tag-dragon',
        dark: 'bg-custom-tag-dark',
        steel: 'bg-custom-tag-steel',
        fairy: 'bg-custom-tag-fairy',
      },
}